### ISSUE TITLE
urlparse module is renamed to urllib.parse in Python 3

### ISSUE THREAD

**Issue by daimajia** [hanguokai/youku#2]
``` python

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/Development/Projects/xxx/youku.py", line 2, in <module>
    from youku import YoukuVideos
  File "/usr/local/lib/python3.5/site-packages/youku/__init__.py", line 1, in <module>
    from .util import YoukuError
  File "/usr/local/lib/python3.5/site-packages/youku/util.py", line 1, in <module>
    import urlparse
ImportError: No module named 'urlparse'

```

**Comment by hanguokai** [comment]
fixed. please upgrade to 0.0.9 from pip to test.

**Comment by daimajia** [comment]
Awesome, thanks for your working on this.

**Comment by daimajia** [comment]
``` python

Traceback (most recent call last):
  File "/Users/daimajia/Development/Projects/xxx/xxx.py", line 4, in <module>
    from youku import YoukuVideos
  File "/usr/local/lib/python3.5/site-packages/youku/__init__.py", line 11, in <module>
    from .youku_videos import YoukuVideos
  File "/usr/local/lib/python3.5/site-packages/youku/youku_videos.py", line 7, in <module>
    from util import check_error, remove_none_value
ImportError: No module named 'util'

```

Can not find module named `util`, try the following `import`:

``` python

from .util import check_error, remove_none_value

```

instead of 

``` python

from util import check_error, remove_none_value

```

**Comment by hanguokai** [comment]
fixed. please upgrade to 0.0.10. 
thanks.
