### ISSUE TITLE
key type is removed from error response and causes error

### ISSUE THREAD

**Issue by peterjpxie** [hanguokai/youku#7]
The change in error response is detected on Sept 26, 2019.

key 'type' is removed from error response.
For example, give wrong access_token, you will get below response without "type" in error.
{"error":{"code":1008,"description":"Access token invalid"}}

Thus we have below error.
### Error:
```
Traceback (most recent call last):
  File "upload.py", line 113, in main
    upload.upload()
  File "upload.py", line 53, in upload
    yk.upload(self.file_info)
  File "/usr/local/lib/python3.7/dist-packages/youku/youku_upload.py", line 361, in upload
    self.create(self.prepare_video_params(**params))
  File "/usr/local/lib/python3.7/dist-packages/youku/youku_upload.py", line 171, in create
    check_error(r, 201)
  File "/usr/local/lib/python3.7/dist-packages/youku/util.py", line 39, in check_error
    raise YoukuError(error['code'], error['type'],
KeyError: 'type'
```

### Fix Suggestion:
Remove key 'type' from util.py - class YoukuError(Exception).

**Comment by hanguokai** [comment]
Fixed. Please update to new version(0.1.1).
Thanks for pointing this.
